language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t josuevora/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true josuevora/react-test npm test

after_succes:
  - docker build -t josuevora/multi-client ./client
  - docker build -t josuevora/multi-nginx ./client
  - docker build -t josuevora/multi-server ./client
  - docker build -t josuevora/multi-worker ./client

  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-std-in

  - docker push josuevora/multi-client
  - docker push josuevora/multi-nginx
  - docker push josuevora/multi-server
  - docker push josuevora/multi-worker